package ms.soft.presistance;
// Generated Feb 5, 2018 6:26:05 PM by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.Date;

/**
 * RegistrationUser generated by hbm2java
 */
public class RegistrationUser  implements java.io.Serializable {


     private RegistrationUserId id;
     private String fristName;
     private String lastName;
     private String address;
     private String pinCode;
     private String userPassword;
     private Date birthDay;
     private String gender;
     private Blob userImage;
     private String imageName;
     private String mobileNo;
     private Date logDt;

    public RegistrationUser() {
    }

    public RegistrationUser(RegistrationUserId id, String fristName, String lastName, String address, String pinCode, String userPassword, Date birthDay, String gender, Blob userImage, String imageName, String mobileNo, Date logDt) {
       this.id = id;
       this.fristName = fristName;
       this.lastName = lastName;
       this.address = address;
       this.pinCode = pinCode;
       this.userPassword = userPassword;
       this.birthDay = birthDay;
       this.gender = gender;
       this.userImage = userImage;
       this.imageName = imageName;
       this.mobileNo = mobileNo;
       this.logDt = logDt;
    }
   
    public RegistrationUserId getId() {
        return this.id;
    }
    
    public void setId(RegistrationUserId id) {
        this.id = id;
    }
    public String getFristName() {
        return this.fristName;
    }
    
    public void setFristName(String fristName) {
        this.fristName = fristName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPinCode() {
        return this.pinCode;
    }
    
    public void setPinCode(String pinCode) {
        this.pinCode = pinCode;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public Date getBirthDay() {
        return this.birthDay;
    }
    
    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Blob getUserImage() {
        return this.userImage;
    }
    
    public void setUserImage(Blob userImage) {
        this.userImage = userImage;
    }
    public String getImageName() {
        return this.imageName;
    }
    
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }
    public Date getLogDt() {
        return this.logDt;
    }
    
    public void setLogDt(Date logDt) {
        this.logDt = logDt;
    }




}


