package ms.soft.presistance;
// Generated Feb 5, 2018 6:26:05 PM by Hibernate Tools 4.3.1



/**
 * RegistrationUserId generated by hbm2java
 */
public class RegistrationUserId  implements java.io.Serializable {


     private String emailId;
     private String userName;
     private String userAdharCard;

    public RegistrationUserId() {
    }

    public RegistrationUserId(String emailId, String userName, String userAdharCard) {
       this.emailId = emailId;
       this.userName = userName;
       this.userAdharCard = userAdharCard;
    }
   
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserAdharCard() {
        return this.userAdharCard;
    }
    
    public void setUserAdharCard(String userAdharCard) {
        this.userAdharCard = userAdharCard;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RegistrationUserId) ) return false;
		 RegistrationUserId castOther = ( RegistrationUserId ) other; 
         
		 return ( (this.getEmailId()==castOther.getEmailId()) || ( this.getEmailId()!=null && castOther.getEmailId()!=null && this.getEmailId().equals(castOther.getEmailId()) ) )
 && ( (this.getUserName()==castOther.getUserName()) || ( this.getUserName()!=null && castOther.getUserName()!=null && this.getUserName().equals(castOther.getUserName()) ) )
 && ( (this.getUserAdharCard()==castOther.getUserAdharCard()) || ( this.getUserAdharCard()!=null && castOther.getUserAdharCard()!=null && this.getUserAdharCard().equals(castOther.getUserAdharCard()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmailId() == null ? 0 : this.getEmailId().hashCode() );
         result = 37 * result + ( getUserName() == null ? 0 : this.getUserName().hashCode() );
         result = 37 * result + ( getUserAdharCard() == null ? 0 : this.getUserAdharCard().hashCode() );
         return result;
   }   


}


